### ISSUE TITLE
Bug with biomes? Worked back in 1.16

### ISSUE THREAD

**Issue by trilliumhq** [rutgerkok/WorldGeneratorApi#49]
**Describe the bug**
`[00:07:22] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception initializing level
	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:674) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:609) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-157]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.biome.BiomeBase.b()" because "biomebase" is null
	at net.minecraft.server.MinecraftServer.lambda$setInitialSpawn$5(MinecraftServer.java:708) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.world.level.biome.BiomeSource.findBiomeHorizontal(BiomeSource.java:121) ~[app:?]
	at net.minecraft.world.level.biome.BiomeSource.findBiomeHorizontal(BiomeSource.java:85) ~[app:?]
	at net.minecraft.server.MinecraftServer.setInitialSpawn(MinecraftServer.java:707) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:660) ~[patched_1.17.1.jar:git-Paper-157]
	... 5 more
[00:07:22] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.biome.BiomeBase.b()" because "biomebase" is null
	at net.minecraft.server.MinecraftServer.lambda$setInitialSpawn$5(MinecraftServer.java:708) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.world.level.biome.BiomeSource.findBiomeHorizontal(BiomeSource.java:121) ~[app:?]
	at net.minecraft.world.level.biome.BiomeSource.findBiomeHorizontal(BiomeSource.java:85) ~[app:?]
	at net.minecraft.server.MinecraftServer.setInitialSpawn(MinecraftServer.java:707) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:660) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:609) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-157]
	at java.lang.Thread.run(Thread.java:831) [?:?]`

**To Reproduce**
Listener 

`public class PancakeMain extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onWorldGeneratorInit(WorldGeneratorInitEvent event) {
        event.getWorldGenerator().setBiomeGenerator(new YourBiomeGenerator());
    }

}`

My Biome Generator

`public class YourBiomeGenerator implements BiomeGenerator {

    @Override
    public Biome getZoomedOutBiome(int x, int y, int z) {
        Biome[] biomes = Biome.values();
        int length = biomes.length;
        int randIndex = new Random().nextInt(length);
            return biomes[randIndex];
    }

    @Override
    public ImmutableSet<Biome> getStructureBiomes() {
        return ImmutableSet.of(Biome.OCEAN,Biome.PLAINS,Biome.DESERT,Biome.MOUNTAINS,Biome.FOREST,Biome.TAIGA,Biome.SWAMP,Biome.RIVER,Biome.NETHER_WASTES,Biome.THE_END,Biome.FROZEN_OCEAN,Biome.FROZEN_RIVER,Biome.SNOWY_TUNDRA,Biome.SNOWY_MOUNTAINS,Biome.MUSHROOM_FIELDS,Biome.MUSHROOM_FIELD_SHORE,Biome.BEACH,Biome.DESERT_HILLS,Biome.WOODED_HILLS,Biome.TAIGA_HILLS,Biome.MOUNTAIN_EDGE,Biome.JUNGLE,Biome.JUNGLE_HILLS,Biome.JUNGLE_EDGE,Biome.DEEP_OCEAN,Biome.STONE_SHORE,Biome.SNOWY_BEACH,Biome.BIRCH_FOREST,Biome.BIRCH_FOREST_HILLS,Biome.DARK_FOREST,Biome.SNOWY_TAIGA,Biome.SNOWY_TAIGA_HILLS,Biome.GIANT_TREE_TAIGA,Biome.GIANT_TREE_TAIGA_HILLS,Biome.WOODED_MOUNTAINS,Biome.SAVANNA,Biome.SAVANNA_PLATEAU,Biome.BADLANDS,Biome.WOODED_BADLANDS_PLATEAU,Biome.BADLANDS_PLATEAU,Biome.SMALL_END_ISLANDS,Biome.END_MIDLANDS,Biome.END_HIGHLANDS,Biome.END_BARRENS,Biome.WARM_OCEAN,Biome.LUKEWARM_OCEAN,Biome.COLD_OCEAN,Biome.DEEP_WARM_OCEAN,Biome.DEEP_LUKEWARM_OCEAN,Biome.DEEP_COLD_OCEAN,Biome.DEEP_FROZEN_OCEAN,Biome.THE_VOID,Biome.SUNFLOWER_PLAINS,Biome.DESERT_LAKES,Biome.GRAVELLY_MOUNTAINS,Biome.FLOWER_FOREST,Biome.TAIGA_MOUNTAINS,Biome.SWAMP_HILLS,Biome.ICE_SPIKES,Biome.MODIFIED_JUNGLE,Biome.MODIFIED_JUNGLE_EDGE,Biome.TALL_BIRCH_FOREST,Biome.TALL_BIRCH_HILLS,Biome.DARK_FOREST_HILLS,Biome.SNOWY_TAIGA_MOUNTAINS,Biome.GIANT_SPRUCE_TAIGA,Biome.GIANT_SPRUCE_TAIGA_HILLS,Biome.MODIFIED_GRAVELLY_MOUNTAINS,Biome.SHATTERED_SAVANNA,Biome.SHATTERED_SAVANNA_PLATEAU,Biome.ERODED_BADLANDS,Biome.MODIFIED_WOODED_BADLANDS_PLATEAU,Biome.MODIFIED_BADLANDS_PLATEAU,Biome.BAMBOO_JUNGLE,Biome.BAMBOO_JUNGLE_HILLS,Biome.SOUL_SAND_VALLEY,Biome.CRIMSON_FOREST,Biome.WARPED_FOREST,Biome.BASALT_DELTAS);
    }

}`

**Comment by rutgerkok** [comment]
Bukkit added `Biome.CUSTOM` to accomodate world generation data packs. You cannot place that biome, as Bukkit doesn't know which one it actually is. So that's likely why it fails.

**Comment by trilliumhq** [comment]
> 
> 
> Bukkit added `Biome.CUSTOM` to accomodate world generation data packs. You cannot place that biome, as Bukkit doesn't know which one it actually is. So that's likely why it fails.
> 
> So if you check for that biome first, and reroll if you got it, it should be fine.

    int length = biomes.length-1;

Fixed it.
