### ISSUE TITLE
Can't compil api-version 1.15, generator.setBaseChunkGenerator deprecated

### ISSUE THREAD

**Issue by tdautreme** [rutgerkok/WorldGeneratorApi#6]
![deprecated](https://user-images.githubusercontent.com/26675498/79040454-db4b5d80-7be8-11ea-9349-49357a154f06.png)
![exception](https://user-images.githubusercontent.com/26675498/79040455-dc7c8a80-7be8-11ea-938b-512a92dd47b2.PNG)

**Describe the bug**
Your api make my plugin exception, and generator.setBaseChunkGenerator warning:
[11:28:34] [Server thread/ERROR]: Could not load 'plugins\SkyClan_MapGenerator.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: WorldGeneratorApi
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:269) [spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353) [spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241

**To Reproduce**
Compil spigot BuildTools.jar in 1.15.2, create a plugin with api-version 1.15
Add your api in my project

**Screenshots**

**Comment by rutgerkok** [comment]
Makes sense, as I never uploaded a release for Minecraft 1.15. I've now done this: version 0.4 should work on Minecraft 1.15.

**Comment by rutgerkok** [comment]
Oh, a second thing: in your code setBaseChunkGenerator should be setBaseTerrainGenerator.
